[package]
name = "multitask"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

[dependencies]
#zellij-tile = {version = "0.38.0", path="/home/aram/code/zellij/zellij-tile"}
zellij-tile = "0.37.1"
